//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kusach
{
    using System;
    using System.Collections.Generic;
    
    public partial class specifsbor_ed
    {
        public int idspecifsbor_ed { get; set; }
        public string count { get; set; }
        public int izdelia_idizdelia { get; set; }
    
        public virtual izdelia izdelia { get; set; }
    }
}
