//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kusach
{
    using System;
    using System.Collections.Generic;
    
    public partial class furnitura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public furnitura()
        {
            this.specifikfurniture = new HashSet<specifikfurniture>();
        }
    
        public int idfurnitura { get; set; }
        public string articul { get; set; }
        public string name { get; set; }
        public string count { get; set; }
        public string izmered { get; set; }
        public string type { get; set; }
        public string cost { get; set; }
        public string izobr { get; set; }
        public string ves { get; set; }
        public int postavchik_idpostavchik { get; set; }
    
        public virtual postavchik postavchik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<specifikfurniture> specifikfurniture { get; set; }
        public override string ToString()
        {
            return name;
        }
    }
}
