//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kusach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tochnokursachEntities : DbContext
    {
        public tochnokursachEntities()
            : base("name=tochnokursachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<furnitura> furnitura { get; set; }
        public virtual DbSet<izdelia> izdelia { get; set; }
        public virtual DbSet<material> material { get; set; }
        public virtual DbSet<oborudovanie> oborudovanie { get; set; }
        public virtual DbSet<postavchik> postavchik { get; set; }
        public virtual DbSet<specificmater> specificmater { get; set; }
        public virtual DbSet<specificoperation> specificoperation { get; set; }
        public virtual DbSet<specifikfurniture> specifikfurniture { get; set; }
        public virtual DbSet<specifsbor_ed> specifsbor_ed { get; set; }
        public virtual DbSet<typeoborud> typeoborud { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<zakaz> zakaz { get; set; }
    }
}
