//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kusach
{
    using System;
    using System.Collections.Generic;
    
    public partial class oborudovanie
    {
        public int idoborudovanie { get; set; }
        public string markirovka { get; set; }
        public string haracteristic { get; set; }
        public int typeoborud_idtypeoborud { get; set; }
    
        public virtual typeoborud typeoborud { get; set; }
    }
}
