//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kusach
{
    using System;
    using System.Collections.Generic;
    
    public partial class postavchik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public postavchik()
        {
            this.furnitura = new HashSet<furnitura>();
            this.material = new HashSet<material>();
        }
    
        public int idpostavchik { get; set; }
        public string name { get; set; }
        public string adress { get; set; }
        public System.DateTime datedostav { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<furnitura> furnitura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<material> material { get; set; }
        public override string ToString()
        {
            return name;
        }
    }
}
