//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kusach
{
    using System;
    using System.Collections.Generic;
    
    public partial class specificoperation
    {
        public int idspecificoperation { get; set; }
        public string operation { get; set; }
        public System.TimeSpan timeoper { get; set; }
        public int izdelia_idizdelia { get; set; }
        public int typeoborud_idtypeoborud { get; set; }
    
        public virtual izdelia izdelia { get; set; }
        public virtual typeoborud typeoborud { get; set; }
    }
}
